<?php

/**
 * BaseSeo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $h1
 * @property string $title
 * @property string $description
 * @property text $body
 * 
 * @method string getUrl()         Returns the current record's "url" value
 * @method string getH1()          Returns the current record's "h1" value
 * @method string getTitle()       Returns the current record's "title" value
 * @method string getDescription() Returns the current record's "description" value
 * @method text   getBody()        Returns the current record's "body" value
 * @method Seo    setUrl()         Sets the current record's "url" value
 * @method Seo    setH1()          Sets the current record's "h1" value
 * @method Seo    setTitle()       Sets the current record's "title" value
 * @method Seo    setDescription() Sets the current record's "description" value
 * @method Seo    setBody()        Sets the current record's "body" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seo');
        $this->hasColumn('url', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
        $this->hasColumn('h1', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('title', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('description', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}