<?php

/**
 * BaseRegList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $address
 * @property Doctrine_Collection $DomainList
 * 
 * @method string              getAddress()    Returns the current record's "address" value
 * @method Doctrine_Collection getDomainList() Returns the current record's "DomainList" collection
 * @method RegList             setAddress()    Sets the current record's "address" value
 * @method RegList             setDomainList() Sets the current record's "DomainList" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reg_list');
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DomainList', array(
             'local' => 'id',
             'foreign' => 'reg_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}