<?php

/**
 * BaseNotificationsEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property boolean $is_active
 * 
 * @method string             getEmail()     Returns the current record's "email" value
 * @method boolean            getIsActive()  Returns the current record's "is_active" value
 * @method NotificationsEmail setEmail()     Sets the current record's "email" value
 * @method NotificationsEmail setIsActive()  Sets the current record's "is_active" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotificationsEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notifications_email');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}