<?php

/**
 * BasePeriod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $period
 * @property Doctrine_Collection $ClientList
 * 
 * @method string              getTitle()      Returns the current record's "title" value
 * @method integer             getPeriod()     Returns the current record's "period" value
 * @method Doctrine_Collection getClientList() Returns the current record's "ClientList" collection
 * @method Period              setTitle()      Sets the current record's "title" value
 * @method Period              setPeriod()     Sets the current record's "period" value
 * @method Period              setClientList() Sets the current record's "ClientList" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeriod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('period');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('period', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClientList', array(
             'local' => 'id',
             'foreign' => 'period_id'));
    }
}