<?php

/**
 * BaseRegListId
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $reg_id
 * 
 * @method integer   getRegId()  Returns the current record's "reg_id" value
 * @method RegListId setRegId()  Sets the current record's "reg_id" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegListId extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reg_list_id');
        $this->hasColumn('reg_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}