<?php

/**
 * BaseTestItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $test_id
 * @property Test $Test
 * 
 * @method string   getTitle()   Returns the current record's "title" value
 * @method integer  getTestId()  Returns the current record's "test_id" value
 * @method Test     getTest()    Returns the current record's "Test" value
 * @method TestItem setTitle()   Sets the current record's "title" value
 * @method TestItem setTestId()  Sets the current record's "test_id" value
 * @method TestItem setTest()    Sets the current record's "Test" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTestItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test_item');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('test_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Test', array(
             'local' => 'test_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}