<?php

/**
 * BaseServerList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $ip_address
 * @property string $comment
 * 
 * @method string     getTitle()      Returns the current record's "title" value
 * @method string     getIpAddress()  Returns the current record's "ip_address" value
 * @method string     getComment()    Returns the current record's "comment" value
 * @method ServerList setTitle()      Sets the current record's "title" value
 * @method ServerList setIpAddress()  Sets the current record's "ip_address" value
 * @method ServerList setComment()    Sets the current record's "comment" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServerList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('server_list');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ip_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('comment', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}