<?php

/**
 * BaseDomainList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $domain
 * @property date $expires_at
 * @property string $server
 * @property integer $reg_id
 * @property integer $client_id
 * @property datetime $sslexp
 * @property datetime $last_check
 * @property ClientList $ClientList
 * @property RegList $RegList
 * 
 * @method string     getDomain()     Returns the current record's "domain" value
 * @method date       getExpiresAt()  Returns the current record's "expires_at" value
 * @method string     getServer()     Returns the current record's "server" value
 * @method integer    getRegId()      Returns the current record's "reg_id" value
 * @method integer    getClientId()   Returns the current record's "client_id" value
 * @method datetime   getSslexp()     Returns the current record's "sslexp" value
 * @method datetime   getLastCheck()  Returns the current record's "last_check" value
 * @method ClientList getClientList() Returns the current record's "ClientList" value
 * @method RegList    getRegList()    Returns the current record's "RegList" value
 * @method DomainList setDomain()     Sets the current record's "domain" value
 * @method DomainList setExpiresAt()  Sets the current record's "expires_at" value
 * @method DomainList setServer()     Sets the current record's "server" value
 * @method DomainList setRegId()      Sets the current record's "reg_id" value
 * @method DomainList setClientId()   Sets the current record's "client_id" value
 * @method DomainList setSslexp()     Sets the current record's "sslexp" value
 * @method DomainList setLastCheck()  Sets the current record's "last_check" value
 * @method DomainList setClientList() Sets the current record's "ClientList" value
 * @method DomainList setRegList()    Sets the current record's "RegList" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDomainList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('domain_list');
        $this->hasColumn('domain', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('expires_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('server', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('reg_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sslexp', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('last_check', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ClientList', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('RegList', array(
             'local' => 'reg_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}