<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $alias
 * @property string $body
 * @property boolean $is_activated
 * 
 * @method string  getTitle()        Returns the current record's "title" value
 * @method string  getAlias()        Returns the current record's "alias" value
 * @method string  getBody()         Returns the current record's "body" value
 * @method boolean getIsActivated()  Returns the current record's "is_activated" value
 * @method Page    setTitle()        Sets the current record's "title" value
 * @method Page    setAlias()        Sets the current record's "alias" value
 * @method Page    setBody()         Sets the current record's "body" value
 * @method Page    setIsActivated()  Sets the current record's "is_activated" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('alias', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 50000, array(
             'type' => 'string',
             'length' => 50000,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}