<?php

/**
 * BaseClientList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_paid
 * @property date $paidtill
 * @property string $name
 * @property string $email
 * @property integer $plan_id
 * @property integer $period_id
 * @property Period $Period
 * @property HostingPlans $HostingPlans
 * @property Doctrine_Collection $DomainList
 * 
 * @method boolean             getIsPaid()       Returns the current record's "is_paid" value
 * @method date                getPaidtill()     Returns the current record's "paidtill" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getEmail()        Returns the current record's "email" value
 * @method integer             getPlanId()       Returns the current record's "plan_id" value
 * @method integer             getPeriodId()     Returns the current record's "period_id" value
 * @method Period              getPeriod()       Returns the current record's "Period" value
 * @method HostingPlans        getHostingPlans() Returns the current record's "HostingPlans" value
 * @method Doctrine_Collection getDomainList()   Returns the current record's "DomainList" collection
 * @method ClientList          setIsPaid()       Sets the current record's "is_paid" value
 * @method ClientList          setPaidtill()     Sets the current record's "paidtill" value
 * @method ClientList          setName()         Sets the current record's "name" value
 * @method ClientList          setEmail()        Sets the current record's "email" value
 * @method ClientList          setPlanId()       Sets the current record's "plan_id" value
 * @method ClientList          setPeriodId()     Sets the current record's "period_id" value
 * @method ClientList          setPeriod()       Sets the current record's "Period" value
 * @method ClientList          setHostingPlans() Sets the current record's "HostingPlans" value
 * @method ClientList          setDomainList()   Sets the current record's "DomainList" collection
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_list');
        $this->hasColumn('is_paid', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('paidtill', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('plan_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('period_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Period', array(
             'local' => 'period_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('HostingPlans', array(
             'local' => 'plan_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('DomainList', array(
             'local' => 'id',
             'foreign' => 'client_id'));
    }
}