generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TestItem
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          test_item
    with_doctrine_route:   true
    actions_base_class:    sfActions
    skip: true

    config:
      actions: ~
      fields:
        id: {label: ''}
        title: {label: Название}
        test_id: {label: ''}
      list:
        layout: ~
        title: 'TestItem'
        display: ~
        max_per_page: 100
        object_actions:
          _delete: ~
          _edit: ~
        search:
          fields: false
        export: false
      filter:
        class: false
      form: ~
      edit:
        title: Редактирование 
      new:
        title: Новая
      struct:
        0: {label: 'TestItem', menu_label: 'TestItem', table: 'Test'}