<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/02/01 16:40:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=zadanie',
  'username' => 'non-root',
  'password' => 123,
  'name' => 'doctrine',
)),);
