<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/02/01 16:40:54
sfConfig::add(array(
  'image_redactor_sizes' => array (
  'min' => 
  array (
    'width' => 100,
    'height' => 100,
  ),
  'FHD' => 
  array (
    'width' => 1920,
    'height' => 1080,
    'thumbstyle' => 'scale',
  ),
),
));
