<?php
// auto-generated by sfCacheConfigHandler
// date: 2019/02/01 16:49:03
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => true, 'vary' => array ()));

