<?php
// auto-generated by sfCacheConfigHandler
// date: 2019/01/29 13:30:14
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => true, 'vary' => array ()));

