<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/02/01 16:40:59
$this->security = array (
  'reset' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
