<?php

/**
 * ClientList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClientList extends BaseClientList
{
    public function save(Doctrine_Connection $conn = null)
    {
        $now = date_create(date('Y-m-d'));

        if ($this->getPaidtill() > $now){
            $this->setIsPaid(true);
        }
        parent::save($conn); // TODO: Change the autogenerated stub
    }
}
