<?php

/**
 * ServerList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ServerList extends BaseServerList
{
    static private $list = null;
    public static function getList()
    {
        if(self::$list === null){
            self::$list = Doctrine_Query::create()
                ->select('s.*')
                ->from('ServerList s')
                ->fetchArray();
        }
    }
}
