<?php
// auto-generated by sfViewConfigHandler
// date: 2019/01/29 13:40:12
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'default')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'default')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0', false, false);

  $response->addStylesheet('g.css?deploy=1515592038', '', array ());
  $response->addStylesheet('p.css?deploy=1515592038', '', array ());
  $response->addJavascript('jquery-1.10.2.min.js?deploy=1515592038', '', array ());
  $response->addJavascript('init.d.js?deploy=1515592038', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0', false, false);

  $response->addStylesheet('g.css?deploy=1515592038', '', array ());
  $response->addStylesheet('p.css?deploy=1515592038', '', array ());
  $response->addJavascript('jquery-1.10.2.min.js?deploy=1515592038', '', array ());
  $response->addJavascript('init.d.js?deploy=1515592038', '', array ());
}

