<?php

/**
 * BaseUserPermissions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $permission_id
 * 
 * @method integer         getUserId()        Returns the current record's "user_id" value
 * @method integer         getPermissionId()  Returns the current record's "permission_id" value
 * @method UserPermissions setUserId()        Sets the current record's "user_id" value
 * @method UserPermissions setPermissionId()  Sets the current record's "permission_id" value
 * 
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserPermissions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_permissions');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permission_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}