<?php

/**
 * PluginUserGroupUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserGroupUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserGroupUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUserGroupUsers');
    }
}