<?php

/**
 * PluginUserPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserPermissionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserPermissionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUserPermissions');
    }
}