<?php

/**
 * PluginPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPermission');
    }
}