<?php

/**
 * PluginUserLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUserLog');
    }
}