# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    logging_enabled: false
    cache: true
    min_view: true

dev:
  .settings:
    error_reporting: <?php echo ((E_ALL) ^ E_NOTICE ^ E_DEPRECATED ^ E_WARNING)."\n" ?>
    web_debug: false
    cache: true
    logging_enabled: false
    min_view: false

test:
  .settings:
    error_reporting: <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache: false
    web_debug: false

all:
  .settings:
    csrf_secret: 2450ecb2853511b9f9137ee54890608d0b8c62dd
    escaping_strategy: true
    escaping_method: ESC_SPECIALCHARS
    use_database: true
    no_script_name: true
    enabled_modules: [default, csSetting, baseAuth]
    default_culture: ru_RU
    standard_helpers: [Partial, Cache, I18N]
    i18n: true
  .actions:
    error_404_module: main
    error_404_action: error404
    login_module: baseAuth
    login_action: signin
    secure_module: baseAuth
    secure_action: secure
