<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sf
 * @subpackage model
 * @author     Atma
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends PluginUser
{
    public function delete(Doctrine_Connection $conn = null)
    {
        foreach (Doctrine_Query::create()->select('ugu.*')->from('UserGroupUsers ugu')->where("ugu.user_id = " . $this->getId())->execute() as $group_link) {
            $group_link->delete();
        }
        return parent::delete($conn);
    }

    public function preSave($event)
    {
        if ($this->getUsername() == '') {
            $this->setUsername($this->getEmail());
        }
        parent::preSave($event);
    }
    public function save(Doctrine_Connection $conn = null)
    {
        return parent::save($conn);
    }

    public function getShortIOF()
    {
        return mb_substr($this->getIname(), 0, 1) . '.' . mb_substr($this->getOname(), 0, 1) . '. ' . $this->getFname();
    }
    public function getPartnerOne()
    {
        return $this->getPartner();
    }
}

