prod:
  logger:
    class: sfNoLogger
    param:
      level: err
      loggers: ~

all:
  storage:
    class: sfSessionStorage
    param:
      session_name: www
  mailer:
    param:
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host: smtp.yandex.ru
          port: 465
          encryption: ssl
          username: umurzakov.farruh@yandex.ru
          password: forproject

  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url: true
      extra_parameters_as_query_string: true
  view_cache:
    class: sfFileCache
    param:
      automatic_cleaning_factor: 0
  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name: true
